---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

namespace: pgadmin

commonLabels:
  namespace: pgadmin
  env: prod

commonAnnotations:
  pgadmin_version: "IMAGE_VERSION_PLACEHOLDER"

imageTags:
  - name: dpage/pgadmin4:stable
    newName: IMAGE_NAME_PLACEHOLDER
    newTag: "IMAGE_VERSION_PLACEHOLDER"

configMapGenerator:
- name: pgadmin-envs
  behavior: merge
  env: env.properties
- name: pgadmin-server-config
  behavior: replace
  files:
    - files/servers.json

secretGenerator:
- name: pgadmin-secrets
  behavior: merge
  env: env_secrets.properties

patchesStrategicMerge:
- patches.yaml