---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pgadmin

commonLabels:
  app: pgadmin

commonAnnotations:
  some-variable: "test"

configMapGenerator:
- name: pgadmin-envs
  env: env.properties
- name: pgadmin-server-config
  files:
    - files/servers.json

secretGenerator:
- name: pgadmin-secrets
  env: env_secrets.properties

resources:
- resources.yaml
