---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  labels:
    app: pgadmin
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:stable
          envFrom:
          - configMapRef:
              name: pgadmin-envs
          - secretRef:
              name: pgadmin-secrets
          ports:
          - name: web
            containerPort: 80
            protocol: TCP
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1
              memory: 512Mi
          volumeMounts:
          - name: pgadmin-server-config
            mountPath: /pgadmin4/servers.json
            subPath: servers.json
      volumes:
        - name: pgadmin-server-config
          configMap:
            name: pgadmin-server-config
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  labels:
    app: pgadmin
spec:
  ports:
  - name: web
    protocol: TCP
    port: 80
    targetPort: web
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pgadmin
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
