---
name: Test GitHub CI aka Github Actions

on: [push]

env:
  SOME_ENV_1: some val1
  SOME_ENV_2: some_val2

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - name: Check out git repository
      uses: actions/checkout@v2

    - name: Lets print OS env - run command in one line
      run: "env | sort"

    - name: Run a multi-line script
      run: |
        #!/bin/bash
        uptime
        whoami

    - name: Build example docker image
      run: |-
        docker build -t some-docker-image:1.0.0 .
    
    - name: Get some info about docker
      run: |-
        docker version
        docker images
        docker ps
    
    - name: Run some docker container in pipeline
      run: |-
        docker run --name httpd -d --rm httpd
        docker ps -a
    
    - name: Lets check in next build if httpd container is still running
      run: "docker ps"

    - name: Print GitHub secret
      run: "echo ${TAJNE_HASLO_DO_KUBERNETESA}"


    - name: Check if we have kubectl already installed on build node
      run: "kubectl version"

    - name: Generate and validate kubernetes configuration file for dev environment
      run: "kubectl kustomize kustomize/overlays/dev"

    - name: Generate and validate kubernetes configuration file for prod environment
      run: "kubectl kustomize kustomize/overlays/prod"