---
name: Test GitHub CI aka Github Actions

on: [push]

env:
  SOURCE_IMAGE_VERSION: 4.22
  IMAGE_VERSION_SUFFIX: oisis
  PGADMIN_DEFAULT_PASSWORD: ${{ secrets.SECRET_1 }}

jobs:
  check-build-environment:
    runs-on: ubuntu-latest
    steps:
    - name: Print OS env
      run: "env | sort"

    - name: Get info about uptime and current user
      run: |
        #!/bin/bash
        uptime
        whoami

    - name: Get info about docker
      run: |-
        #!/bin/bash
        docker version
        docker images
        docker ps

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out git repository
      uses: actions/checkout@v2

    - name: Update FROM image version from env
      run: sed "s/PGADMIN_VERSION/${{ env.SOURCE_IMAGE_VERSION }}/g" -i Dockerfile

    - name: Build example docker image
      run: "docker build -t oisis/pgadmin4:${{ env.SOURCE_IMAGE_VERSION }}-${{ env.IMAGE_VERSION_SUFFIX }} ."
  
  deploy-to-dev:
    runs-on: ubuntu-latest
    environment: dev
    env:
      SECRET_1: ${{ secrets.SECRET_1 }}
    steps:
    - name: Check out git repository
      uses: actions/checkout@v2

    - name: Change password from GitHub secrets - env dev
      run: sed "s/PGADMIN_DEFAULT_PASSWORD_PLACEHOLDER/${{ env.PGADMIN_DEFAULT_PASSWORD }}/g" -i kustomize/overlays/dev/env_secrets.properties

    - name: Update image version
      run: sed "s/IMAGE_VERSION_PLACEHOLDER/${{ env.SOURCE_IMAGE_VERSION }}-${{ env.IMAGE_VERSION_SUFFIX }}/g" -i kustomize/overlays/dev/kustomization.yaml

    - name: Generate and validate kubernetes configuration file for dev environment
      run: "kubectl kustomize kustomize/overlays/dev"

  deploy-to-prod:
    runs-on: ubuntu-latest
    environment: prod
    env:
      SECRET_1: ${{ secrets.SECRET_1 }}
    steps:
    - name: Check out git repository
      uses: actions/checkout@v2

    - name: Change password from GitHub secrets - env prod
      run: sed "s/PGADMIN_DEFAULT_PASSWORD_PLACEHOLDER/${{ env.PGADMIN_DEFAULT_PASSWORD }}/g" -i kustomize/overlays/prod/env_secrets.properties

    - name: Update image version
      run: sed "s/IMAGE_VERSION_PLACEHOLDER/${{ env.SOURCE_IMAGE_VERSION }}-${{ env.IMAGE_VERSION_SUFFIX }}/g" -i kustomize/overlays/prod/kustomization.yaml

    - name: Generate and validate kubernetes configuration file for prod environment
      run: "kubectl kustomize kustomize/overlays/prod"
