---
name: Test GitHub CI aka Github Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Lets print OS env - run command in one line
      run: "env | sort"

    - name: Run a multi-line script
      run: |
        #!/bin/bash
        ls -al /
        uptime
        whoami
